package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Тест на поиск в mail.ru")
    void generatedTest() {
        step("Открыть https://mail.ru", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести \"mosqa.ru\" в поле поиска", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что \"MosQA CTF\" появилось в результатах поиска", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://mail.ru'", () ->
            open("https://mail.ru"));

        step("Page title should have text 'Mail.ru: почта, поиск в интернете, новости, игры'", () -> {
            String expectedTitle = "Mail.ru: почта, поиск в интернете, новости, игры";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://mail.ru'", () ->
            open("https://mail.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}